/* 
CREARE UNA TABELLA DI LIBRI CARATTERIZZATA DA TITOLO,AUTORE E CODICE ISBN.
-INSERIRE ALMENO 6 LIBRI
-RICERCARE TUTTI I LIBRI DI UN AUTORE
-RICERCARE TUTTI I LIBRI CHE HANNO LA SEQUENZA AN AL LORO INTERNO
-RICERCA PER ISBN
*/

-- CREATE DATABASE lez_03_Biblioteca
-- USE lez_03_Biblioteca


CREATE TABLE Libri(
	libroID INTEGER PRIMARY KEY IDENTITY,
	titolo VARCHAR(250) NOT NULL,
	autore VARCHAR(250) NOT NULL, 
	isbn VARCHAR(250) NOT NULL UNIQUE
)

INSERT INTO Libri(titolo,autore,isbn) VALUES 
	('1984', 'George Orwell', '9781234567897'),
	('Orgoglio e pregiudizio', 'Jane Austen', '9781212367897'),
	('Ragione e sentimento', 'Jane Austen', '9781234567823'),
	('Soffocare', 'Chuck Palanhiuk', '9781234567961'),
	('La coscienza di Zeno', 'Italo Svevo', '9781234567891'),
	('Dune', 'Frank Herbert', '9787234567897')


SELECT * FROM Libri;

-- RICERCARE TUTTI I LIBRI DI UN AUTORE
SELECT * FROM Libri
	WHERE autore = 'Jane Austen'

--RICERCARE TUTTI I LIBRI CHE HANNO LA SEQUENZA AN AL LORO INTERNO
SELECT * FROM Libri
	WHERE titolo LIKE '%an%' OR autore LIKE '%an%'

--RICERCARE PER ISBN
SELECT isbn FROM LIBRI

--AGGIUNGO CAMPO CATEGORIA
ALTER TABLE Libri ADD categoria VARCHAR(250) DEFAULT 'N.D.';

SELECT * FROM Libri WHERE categoria IS NOT NULL
SELECT * FROM Libri WHERE categoria IS NULL

--AGGIUNGO CAMPO CATEGORIA
ALTER TABLE Libri ADD pagine INTEGER;

ALTER TABLE Libri ADD anno INTEGER DEFAULT 'N.D.';

ALTER TABLE Libri
	DROP COLUMN anno;





